name: super_network_logger
description: A Dio interceptor for logging network calls with color, styling and formatting support.
version: 1.0.0
homepage: "https://github.com/navneet-singh-profile/super_network_logger"

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  colorize: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
